# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StockApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.2'
  pod 'Kingfisher', '~> 6.0'

  # Google login
  pod 'GoogleSignIn'
  
  # Facebook login
  pod 'FBSDKLoginKit'
  pod 'FBSDKCoreKit'
  
  # Pods for StockApp

  target 'StockAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StockAppUITests' do
    # Pods for testing
  end

end
